name: Sync Tracker Lists

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: # 支持手动触发
  push:
    branches: [ main ]

jobs:
  sync-trackers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 获取完整历史记录以便比较更改
    
        
    - name: Download all.txt
      run: |
        curl -s "https://raw.githubusercontent.com/XIU2/TrackersListCollection/refs/heads/master/all.txt" -o trackerlist/all.txt
        echo "Downloaded all.txt with $(wc -l < trackerlist/all.txt) lines"
        
    - name: Download best.txt
      run: |
        curl -s "https://raw.githubusercontent.com/XIU2/TrackersListCollection/refs/heads/master/best.txt" -o trackerlist/best.txt
        echo "Downloaded best.txt with $(wc -l < trackerlist/best.txt) lines"
        
    - name: Download http.txt
      run: |
        curl -s "https://raw.githubusercontent.com/XIU2/TrackersListCollection/refs/heads/master/http.txt" -o trackerlist/http.txt
        echo "Downloaded http.txt with $(wc -l < trackerlist/http.txt) lines"
        
    - name: Download nohttp.txt
      run: |
        curl -s "https://raw.githubusercontent.com/XIU2/TrackersListCollection/refs/heads/master/nohttp.txt" -o trackerlist/nohttp.txt
        echo "Downloaded nohttp.txt with $(wc -l < trackerlist/nohttp.txt) lines"
        
    - name: Commit and Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update tracker lists"
        directory: trackerlist
        
    - name: Trigger Other Workflow-giteed
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: sync-to-gitee.yml # 其他工作流的文件名
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Other Workflow-gitcode
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: syn-to-gitcode.yml # 其他工作流的文件名
        token: ${{ secrets.GITHUB_TOKEN }}